"""
Constants for external file formats (XML structure and file names).
"""


class ExternalFiles:
    SPRITEINFO_FILE = "spriteinfo.xml"
    ANIMATIONS_FILE = "animations.xml"
    FRAMES_FILE = "frames.xml"
    OFFSETS_FILE = "offsets.xml"
    IMGSINFO_FILE = "imgsinfo.xml"
    IMGS_DIR = "imgs"
    PALETTE_FILE = "palette.pal"


class XmlRoot:
    SPRPROPS = "SpriteProperties"
    ANIMDAT = "AnimData"
    FRMLST = "FrameList"
    OFFLST = "OffsetList"
    IMGINFO = "ImagesInfo"


class XmlNode:
    ANIMGRPTBL = "AnimGroupTable"
    ANIMGRP = "AnimGroup"
    ANIMSEQTBL = "AnimSequenceTable"
    ANIMSEQ = "AnimSequence"
    ANIMFRM = "AnimFrame"
    FRMGRP = "FrameGroup"
    FRAME = "Frame"
    OFFSET = "Offset"
    IMAGE = "ImageProperty"
    SPRITE = "Sprite"
    SHADOW = "Shadow"
    RESOLUTION = "Resolution"


class XmlProp:
    IMGINDEX = "ImageIndex"
    UNK0 = "Unk0"
    OFFSETY = "OffsetY"
    OFFSETX = "OffsetX"
    OFFSET_X = "X"
    OFFSET_Y = "Y"
    PALOFFSET = "PaletteOffset"
    MEMOFFSET = "MemoryOffset"
    WIDTH = "Width"
    HEIGHT = "Height"
    HFLIP = "HFlip"
    VFLIP = "VFlip"
    MOSAIC = "Mosaic"
    ISABSOLUTEPALETTE = "IsAbsolutePalette"
    XOFFBIT7 = "XOffsetBit7"
    YOFFBIT3 = "YOffsetBit3"
    YOFFBIT5 = "YOffsetBit5"
    YOFFBIT6 = "YOffsetBit6"
    DURATION = "Duration"
    METAGRPIND = "MetaFrameGroupIndex"
    UNK3 = "Unk3"
    MAXCOLUSED = "MaxColorsUsed"
    UNK4 = "Unk4"
    UNK5 = "Unk5"
    MAXMEMUSED = "MaxMemoryUsed"
    UNK7 = "Unk7"
    UNK8 = "Unk8"
    UNK9 = "Unk9"
    UNK10 = "Unk10"
    SPRTY = "SpriteType"
    IS8BPPSPRITE = "Is8bppSprite"
    TILESMODE = "TilesMode"
    PALSLOTSUSED = "PaletteSlotsUsed"
    UNK12 = "Unk12"
    ZINDEX = "ZIndex"
    ANIMSEQIND = "AnimSequenceIndex"
