"""
Constants for external file formats (XML structure and file names).
"""


class ExternalFiles:
    SPRITEINFO_FILE = "spriteinfo.xml"
    ANIMATIONS_FILE = "animations.xml"
    FRAMES_FILE = "frames.xml"
    OFFSETS_FILE = "offsets.xml"
    IMGSINFO_FILE = "imgsinfo.xml"
    IMGS_DIR = "imgs"
    PALETTE_FILE = "palette.pal"


class XmlRoot:
    SPRPROPS = "SpriteProperties"
    ANIMDAT = "AnimData"
    FRMLST = "FrameList"
    OFFLST = "OffsetList"
    IMGINFO = "ImagesInfo"


class XmlNode:
    ANIMGRPTBL = "AnimGroupTable"
    ANIMGRP = "AnimGroup"
    ANIMSEQTBL = "AnimSequenceTable"
    ANIMSEQ = "AnimSequence"
    ANIMFRM = "AnimFrame"
    FRMGRP = "FrameGroup"
    FRAME = "Frame"
    OFFSET = "Offset"
    IMAGE = "ImageProperty"
    SPRITE = "Sprite"
    SHADOW = "Shadow"
    RESOLUTION = "Resolution"


class XmlProp:
    IMGINDEX = "ImageIndex"
    UNK0 = "Unk0"
    OFFSETY = "OffsetY"
    OFFSETX = "OffsetX"
    OFFSET_X = "X"
    OFFSET_Y = "Y"
    PALOFFSET = "PaletteOffset"
    MEMOFFSET = "MemoryOffset"
    WIDTH = "Width"
    HEIGHT = "Height"
    HFLIP = "HFlip"
    VFLIP = "VFlip"
    MOSAIC = "Mosaic"
    ISABSOLUTEPALETTE = "IsAbsolutePalette"
    CONST0_XOFFBIT7 = "Const0_XOffsetBit7"
    BOOL_YOFFBIT3 = "Bool_YOffsetBit3"
    CONST0_YOFFBIT5 = "Const0_YOffsetBit5"
    CONST0_YOFFBIT6 = "Const0_YOffsetBit6"
    DURATION = "Duration"
    METAGRPIND = "MetaFrameGroupIndex"
    BOOL_UNK3 = "Bool_Unk3"
    MAXCOLUSED = "MaxColorsUsed"
    UNK4 = "Unk4"
    UNK5 = "Unk5"
    MAXMEMUSED = "MaxMemoryUsed"
    CONST0_UNK7 = "Const0_Unk7"
    CONST0_UNK8 = "Const0_Unk8"
    BOOL_UNK9 = "Bool_Unk9"
    CONST0_UNK10 = "Const0_Unk10"
    SPRTY = "SpriteType"
    IS8BPPSPRITE = "Is8bppSprite"
    TILESMODE = "TilesMode"
    PALSLOTSUSED = "PaletteSlotsUsed"
    CONST0_UNK12 = "Const0_Unk12"
    ZINDEX = "ZIndex"
    ANIMSEQIND = "AnimSequenceIndex"
